# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 42

n_timesteps: !!float 1.5e6 #og 1e6
policy: 'MlpPolicy'
n_steps: 512 #original 16
batch_size: 64  #4096
gae_lambda: 0.95
gamma: 0.99
n_epochs: 10 #20
ent_coef: 0.005  #0.01
learning_rate: !!float 3e-4
clip_range: !!float 0.2
policy_kwargs:
  activation_fn: 'nn.ELU'
  net_arch: [64, 64]  #[32,32]
  squash_output: False
vf_coef: 1.0
max_grad_norm: 1.0
device: "cuda:0"
